config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/about' => 'homes#about'
  root 'homes#top'
  get 'search' => "searchs#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :follow, :follower
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 199 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def following?(user)
    follower.where(followed_id: user.id).exists?
  end

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end

	def after_sign_in_path_for(resource)
		user_path(resource.id)
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = @book.id
		comment.save
        @book_comments = @book.book_comments
		render :comment
	end

	def destroy
		BookComment.find_by(book_id: params[:book_id],id: params[:id]).destroy
        @book = Book.find(params[:book_id])
        @book_comments = @book.book_comments
		render :comment
	end


	private
	def book_comment_params
		params.require(:book_comment).permit(:comment, :book_id, :user_id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]

  def index
      @user = User.find(current_user.id)
      @books = Book.all.order(id: "DESC")
  	  @book = Book.new
  end

  def show
      @book = Book.new
      @books = Book.find(params[:id])
      @user = User.find(@books.user.id)
      @book_comment = BookComment.new
      @book_comments = @books.book_comments
  end

  def edit
      @book = Book.find(params[:id])
  end

  def create
  	  @book = Book.new(book_params)
      @book.user_id = current_user.id
  	  if @book.save
  	     redirect_to book_path(@book.id), notice: 'You have creatad book successfully.'
      else
         @user = User.find(current_user.id)
         @books = Book.all.order(id: "DESC")
         render action: :index
      end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
         redirect_to book_path(@book.id), notice: 'You have updated user successfully.'
      else
         render action: :edit
      end
  end



    private
    def correct_user
        @books = Book.find(params[:id])
        user = User.find(@books.user.id)
        if current_user == user
        else
           redirect_to books_path
        end
    end

    def book_params
    	  params.require(:book).permit(:title, :body, :user_id)
    end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@books = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @books.id)
		favorite.save
	end

	def destroy
		@books = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @books.id)
		favorite.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		user = User.find(params[:user_id])
		follow = current_user.followed.new(follower_id: user.id)
		follow.save
		redirect_back(fallback_location:root_path)
	end

	def destroy
		user = User.find(params[:user_id])
		follow = current_user.followed.find_by(follower_id: user.id)
		follow.destroy
		redirect_back(fallback_location:root_path)
	end

	def follow
		@users = User.where(followed_id: :id)
	end


	private
	def relationship_params
		params.require(:relationship).permit(:followed_id, :follower_id)
	end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
      if params[:or] == "Users"
      	 if params[:how] == "完全一致"
            @users = User.where('name LIKE ?', "#{params[:name]}")
         elsif params[:how] == "前方一致"
         	@users = User.where('name LIKE ?', "#{params[:name]}%")
         elsif params[:how] == "後方一致"
         	@users = User.where('name LIKE ?', "%#{params[:name]}")
         else
         	@users = User.where('name LIKE ?', "%#{params[:name]}%")
         end

      else
      	 if params[:how] == "完全一致"
            @books = Book.where('title LIKE ?', "#{params[:name]}")
      	 elsif params[:how] == "前方一致"
      	 	@books = Book.where('title LIKE ?', "#{params[:name]}%")
      	 elsif params[:how] == "後方一致"
      	 	@books = Book.where('title LIKE ?', "%#{params[:name]}")
      	 else
      	 	@books = Book.where('title LIKE ?', "%#{params[:name]}%")
      	 end
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]


  def show
      @user = User.find(params[:id])
      @book = Book.new
      @books = @user.books.all.reverse_order
  end

  def index
      @book = Book.new
      @user = User.find(current_user.id)
      @users = User.all.order(id: "DESC")
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
      else
         render action: :edit
      end
  end

  def follow
      @user = User.find(params[:id])
      @users = @user.follower_user
  end

  def follower
      @user = User.find(params[:id])
      @users = @user.following_user
  end


    private
    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end

    def correct_user
        user = User.find(params[:id])
        if current_user == user
        else
           redirect_to user_path(current_user.id)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
	<% @book_comments.each do |book_comments| %>
		<table>

<tr>
          <td><%= attachment_image_tag book_comments.user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %><br>
			<%= book_comments.user.name %>
		  </td>
		  <td>
		  	<%= book_comments.comment %>
		  </td>


		<% if book_comments.user.id == current_user.id %>

		  <td> &nbsp; <%= link_to book_book_comment_path(book_comments.book.id, book_comments.id), method: :delete, remote: true, data: { confirm: '本当に消しますか？'} do %>
		  <button type="button" class="btn btn-sm btn-danger">Destroy</button>

		  </td>
		<% else %>
		  <td></td>
		<% end %>
		<% end %>

		</tr>
				</table>
	<% end %>

app/views/book_comments/_form.html.erb
<%= form_with model: [books, comments] do |f| %>
<p><%= f.text_area :comment %></p>
<%= f.submit "送信" %>
<% end %>

app/views/book_comments/comment.js.erb
$("#comment_area").html("<%= j(render 'book_comments/comment', {comments: @comments}) %>")
$("textarea").val('')

app/views/books/edit.html.erb
<div class="container">
<p id="notice">
	<%= notice %>
</p>

<h2>Editing Book</h2>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
  <p  style="color: red; font-size: 25px;"><%= @book.errors.count %>errors  prohibited this obj from being saved:</p>
  <ul>
  	<% @book.errors.full_messages.each do |message| %>
  	<li style="color: red;"><%= message %></li>
  	<% end %>
  </ul>
  <% end %>
<h5><strong>Title</strong></h5>
<%= f.text_field :title, :size => "100%" %>
<h5><strong>Opinion</strong></h5>
<%= f.text_area :body, :size => "100%" %>

<p><%= f.submit 'Update Book', class: "btn btn-info btn-block"  %></p>

<% end %>

<p><%= link_to "Show", book_path(@book) %>|<%= link_to "Back", '/books' %></p>

app/views/books/index.html.erb
<div class="container">
<div class="row">

<p id="notice">
	<%= notice %>
</p>

<% if @book.errors.any? %>
  <p style="color: red; font-size: 25px;"><%= @book.errors.count %>errors  prohibited this obj from being saved:</p>
  <ul>
  	<% @book.errors.full_messages.each do |message| %>
  	<li style="color: red;"><%= message %></li>
  	<% end %>
  </ul>
  <% end %>



<div class="col-xs-3">
<%= render 'users/side', users: @users %>
</div>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= link_to user_path(book.user_id.to_i) do %>
				<%= attachment_image_tag book.user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'80x80' %>
				<% end %>
				</td>
			<td><%= link_to book_path(book.id) do %>
				<%= book.title %>
				<% end %>
			</td>
			<td><%= book.body %></td>

			<td class="favorites_<%= book.id %>">
			<%= render partial: 'favorites/favorite', locals: { book: book} %>
		</td>

			<td>コメント数:<%= book.book_comments.count %></td>


		</tr>
		<% end %>
	</tbody>
</table>

</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">

<%= render 'layouts/flash' %>



<div class="col-xs-3">
<%= render 'users/side', users: @users %>
</div>

<div class="col-xs-9">
<h1>Book detail</h1>
<table class="table table-striped">
	<tr>
		<td><%= attachment_image_tag @user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %><br><%= link_to user_path(@user) do %>
			<%= @user.name %>
			<% end %></td>
			<td><%= link_to book_path do %>
				<%= @books.title %>
				<% end %>
			</td>
			<td><%= @books.body %></td>

			<td class="favorites_<%= @books.id %>">
			<%= render partial: 'favorites/favorite', locals: { book: @books} %>
			</td>

			<td>コメント数:<%= @books.book_comments.count %></td>


			<% if @books.user.id == current_user.id %>

<td><%= link_to edit_book_path(@books) do %>
<button type="button" class="btn btn-sm btn-success">Edit</button>
<% end %></td>
<td><%= link_to book_path(@books), method: :delete, data: { confirm: '本当に消しますか？'} do %>
<button type="button" class="btn btn-sm btn-danger">Destroy</button>
<% end %></td>

<% end %>

	</tr>
</table>

<p>&nbsp;</p>

<div id="comment_area">

			<%= render partial: 'book_comments/comment', locals: { book_comments: @book_comments} %>

</div>
<%= render partial: 'book_comments/form', locals: { books: @books, comments: @book_comment} %>




</div>
</div>
</div>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
<% if book.favorited_by?(current_user) %>
				<%= link_to book_favorites_path(book), method: :delete,remote: true do %>
					<i class="fas fa-heart" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>

			<% else %>
				<%= link_to book_favorites_path(book), method: :post, remote: true do %>
					<i class="far fa-heart" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>

			<% end %>
			<% end %>

app/views/favorites/create.js.erb
$(".favorites_<%= @books.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {book: @books}) %>");

app/views/favorites/destroy.js.erb
$(".favorites_<%= @books.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {book: @books}) %>");

app/views/homes/about.html.erb
<div class="container">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers!</strong></span></h1>

app/views/homes/index.html.erb
<div class="container">

<%= render 'layouts/flash' %>

	<h2>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers !!</strong></span></h2>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong>,</span><br>
you can share and exchange your opinions,inpressions,and emotions<br>
about various books!</p>



<%= link_to new_user_session_path do %>
<button type="button" class="btn btn-info btn-block">Log in</button>
<% end %>
<%= link_to new_user_registration_path do %>
<button type="button" class="btn btn-success btn-block">Sign up</button>
<% end %>

</div>

app/views/homes/top.html.erb
<div class="container">

<%= render 'layouts/flash' %>

	<h2 class="jquery">welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers !!</strong></span></h2>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong>,</span><br>
you can share and exchange your opinions,inpressions,and emotions<br>
about various books!</p>

<a class="btn btn-info btn-block" href="/users/sign_in">Log in</a>
<a class="btn btn-success btn-block" href="/users/sign_up">Sign up</a>



</div>

app/views/relationships/follow.html.erb
<div class="container">

<h1>Follow Users</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followed.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>

			<td><% if user.following?(current_user) %>
					<%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(user), method: :post %>
				<% end %>
			</td>

			<td><%= link_to "Show", user_path(user) %></td>


		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/searchs/search.html.erb
<h1><%= "#{params[:or]} search for '#{params[:name]}'" %></h1>

<% if params[:or] == "Books" %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= link_to user_path(book.user_id.to_i) do %>
				<%= attachment_image_tag book.user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'80x80' %>
				<% end %>
				</td>
			<td><%= link_to book_path(book) do %>
				<%= book.title %>
				<% end %>
			</td>
			<td><%= book.body %></td>

						<% if book.favorited_by?(current_user) %>
				<td><%= link_to book_favorites_path(book), method: :delete do %>
					<i class="fas fa-heart" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>
				</td>
			<% else %>
				<td><%= link_to book_favorites_path(book), method: :post do %>
					<i class="far fa-heart" aria-hidden="true"></i>
					<%= book.favorites.count %>
					<% end %>
				</td>
			<% end %>

			<td>コメント数:<%= book.book_comments.count %></td>


		</tr>
		<% end %>
	</tbody>
</table>

<% else %>

<table class="table table-striped">
<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followed.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>

			<% if user != current_user %>
			<td><% if user.following?(current_user) %>
					<%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(user), method: :post %>
				<% end %>
			</td>
			<% else %>
			<td></td>
			<% end %>

			<td><%= link_to "Show", user_path(user) %></td>


		</tr>
		<% end %>
	</tbody>
</table>

<% end %>

app/views/users/_side.html.erb
<h2>User info</h2>
<%= form_for(@user) do |user| %>

<p><%= attachment_image_tag @user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'80x80' %></p>
<table style="width: 100%">
	<thead>
		<tr style="border-top: solid 1px gray;">
			<th>name</th><th><%= @user.name %> </th>
		</tr>
		<tr style="border-top: solid 1px gray;">
			<th>introduction</th><th><%= @user.introduction %></th>
		</tr>
		<tr style="border-top: solid 1px gray;">
			<th>follows</th><th><%= link_to follow_user_path(@user) do %><%= @user.followed.count %><% end %></th>
		</tr>
		<tr style="border-top: solid 1px gray;">
			<th>followers</th><th><%= link_to follower_user_path(@user) do %><%= @user.follower.count %><% end %></th>
		</tr>
		<% end %>
	</thead>
</table>

<p> <% if @user.id == current_user.id %>
        <p><%= link_to edit_user_path(@user), class: "btn btn-default btn-block" do %><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        	<% end %></p>

    <% else %>
    <% if @user.following?(current_user) %>

		<p><%= link_to user_relationships_path(@user), method: :delete do %><button type="button" class="btn btn-sm btn-primary">フォローを外す</button>
			<% end %>
		</p>

	<% else %>

		<p><%= link_to user_relationships_path(@user), method: :post do %><button type="button" class="btn btn-sm btn-success">フォローする</button>
			<% end %>
		</p>

	<% end %>



    <% end %></p>





<h2>New book</h2>
<%= form_for(@book) do |f| %>

<h4>Title</h4>
<p><%= f.text_field :title %></p>
<h4>Opinion</h4>
<p><%= f.text_area :body %><p>

<p><%= f.submit 'Create Book', class: "btn btn-info btn-block" %></p>

<% end %>


app/views/users/edit.html.erb
<div class="container">
<h2>User info</h2>

<% if @user.errors.any? %>
  <p style="color: red; font-size: 25px;"><%= @user.errors.count %>errors  prohibited this obj from being saved:</p>
  <ul>
  	<% @user.errors.full_messages.each do |message| %>
  	<li style="color: red;"><%= message %></li>
  	<% end %>
  </ul>
  <% end %>

<%= form_for(@user) do |f| %>
<h5><strong>Name</strong><%= f.text_field :name, autofocus: true %></h5>

<h5><strong>Image</strong></h5>
	<p><%= f.attachment_field :profile_image %></p>
<h5><strong>Introduction</strong><%= f.text_area :introduction, autofocus: true %></h5>




<%= f.submit "Update User" %>
<% end %>

app/views/users/follow.html.erb
<div class="container">

<h1>Follow Users</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>


		<% @users.each do |user| %>

		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followed.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>

			<td><% if user.following?(current_user) %>
					<%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(user), method: :post %>
				<% end %>
			</td>

			<td><%= link_to "Show", user_path(user) %></td>


		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/users/follower.html.erb
<div class="container">

<h1>Follower Users</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>


		<% @users.each do |user| %>

		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followed.count %></td>
			<td>フォロワー数：<%= user.follower.count %></td>

			<td><% if user.following?(current_user) %>
					<%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(user), method: :post %>
				<% end %>
			</td>

			<td><%= link_to "Show", user_path(user) %></td>


		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/users/index.html.erb

<div class="container">
<div class="row">

<div class="col-xs-3">
<%= render 'users/side', users: @users %>
</div>

<div class="col-xs-9">
<h1>Users</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %></td>
			<td><%= user.name %></td> <!--link_to-->
			<td><%= link_to "Show", user_path(user) %></td>


		</tr>
		<% end %>
	</tbody>
</table>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">

<%= render 'layouts/flash' %>



<div class="col-xs-3">
<%= render 'users/side', users: @users %>
</div>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= link_to user_path(book.user_id.to_i) do %>
				<%= attachment_image_tag @user, :profile_image, :fill, 80, 80, format: 'jpeg', fallback: "no-image.jpg",size:'50x50' %>
				<% end %>
				</td>

			<td><%= link_to book_path(book) do %>
				<%= book.title %>
				<% end %>
				</td> <!--link_to-->
			<td><%= book.body %></td>

			<td>コメント数:<%= book.book_comments.count %></td>

		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>