config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/about' => 'homes#about'
  root 'homes#top'
  get 'search' => "searchs#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :follow, :follower
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 199 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def following?(user)
    follower.where(followed_id: user.id).exists?
  end

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end

	def after_sign_in_path_for(resource)
		user_path(resource.id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]

  def index
      @user = User.find(current_user.id)
      @books = Book.all.order(id: "DESC")
  	  @book = Book.new
  end

  def show
      @book = Book.new
      @books = Book.find(params[:id])
      @user = User.find(@books.user.id)
      @book_comment = BookComment.new
      @book_comments = @books.book_comments
  end

  def edit
      @book = Book.find(params[:id])
  end

  def create
  	  @book = Book.new(book_params)
      @book.user_id = current_user.id
  	  if @book.save
  	     redirect_to book_path(@book.id), notice: 'You have creatad book successfully.'
      else
         @user = User.find(current_user.id)
         @books = Book.all.order(id: "DESC")
         render action: :index
      end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
         redirect_to book_path(@book.id), notice: 'You have updated user successfully.'
      else
         render action: :edit
      end
  end



    private
    def correct_user
        @books = Book.find(params[:id])
        user = User.find(@books.user.id)
        if current_user == user
        else
           redirect_to books_path
        end
    end

    def book_params
    	  params.require(:book).permit(:title, :body, :user_id)
    end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@books = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @books.id)
		favorite.save
	end

	def destroy
		@books = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @books.id)
		favorite.destroy
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
      if params[:or] == "Users"
      	 if params[:how] == "完全一致"
            @users = User.where('name LIKE ?', "#{params[:name]}")
         elsif params[:how] == "前方一致"
         	@users = User.where('name LIKE ?', "#{params[:name]}%")
         elsif params[:how] == "後方一致"
         	@users = User.where('name LIKE ?', "%#{params[:name]}")
         else
         	@users = User.where('name LIKE ?', "%#{params[:name]}%")
         end

      else
      	 if params[:how] == "完全一致"
            @books = Book.where('title LIKE ?', "#{params[:name]}")
      	 elsif params[:how] == "前方一致"
      	 	@books = Book.where('title LIKE ?', "#{params[:name]}%")
      	 elsif params[:how] == "後方一致"
      	 	@books = Book.where('title LIKE ?', "%#{params[:name]}")
      	 else
      	 	@books = Book.where('title LIKE ?', "%#{params[:name]}%")
      	 end
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]


  def show
      @user = User.find(params[:id])
      @book = Book.new
      @books = @user.books.all.reverse_order
  end

  def index
      @book = Book.new
      @user = User.find(current_user.id)
      @users = User.all.order(id: "DESC")
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
      else
         render action: :edit
      end
  end

  def follow
      @user = User.find(params[:id])
      @users = @user.follower_user
  end

  def follower
      @user = User.find(params[:id])
      @users = @user.following_user
  end


    private
    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end

    def correct_user
        user = User.find(params[:id])
        if current_user == user
        else
           redirect_to user_path(current_user.id)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/fb62a1856a.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

<header class="navbar navber-fixed-top navbar-inverse">
  <div class="containar-fluid">
  <div class="navbar-brand navbar-left" style="color:#fff">Bookers</div>
  <div class="collapse navbar-collapse">
<ul class="navbar-nav navbar-right">
<% if user_signed_in? %>

  <li class="nav-item">
    <%= link_to user_path(current_user.id), :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-home" aria-hidden="true">&nbsp;Home</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to users_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-user" aria-hidden="true">&nbsp;Users</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to books_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-book" aria-hidden="true">&nbsp;Books</span>
    <% end %>
  </li>
  <li class="nav-item">
   <%= link_to destroy_user_session_path, :class=>"nav-font", method: :delete do %>
   <span class="glyphicon glyphicon-log-out" aria-hidden="true">&nbsp;logout</span>
   <% end %>
  </li>

  <% else %>
  <li class="nav-item">
    <%= link_to root_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-home" aria-hidden="true">&nbsp;Home</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to home_about_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-link" aria-hidden="true">&nbsp;About</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_user_registration_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-edit" aria-hidden="true">&nbsp;sign up</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to new_user_session_path, :class=>"nav-font" do %>
    <span class="glyphicon glyphicon-log-in" aria-hidden="true">&nbsp;login</span>
    <% end %>
  </li>


  <% end %>
</ul>
</div>
</header>

<div class="saerch-bar" style="text-align: center;">
<% if user_signed_in? %>
<%= form_tag(search_path, method: "get") do %>
  <%= text_field_tag(:name) %>
  <%= select_tag(:or, options_for_select([["User","Users"],["Book","Books"]])) %>
  <%= select_tag(:how, options_for_select([["完全一致","完全一致"],["前方一致","前方一致"],["後方一致","後方一致"],["部分一致","部分一致"]])) %>
  <%= submit_tag "検索" %>
<% end %>
<% end %>
</div>


<%= yield %>


<footer>
  <P>CopyRight Infratop.inc</P>
</footer>
</div>
</body>
</html>